apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
