apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: testvm1
  name: dv-vm
spec:
  dataVolumeTemplates:
    - metadata:
        name: awesome-dv
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
        source:
          http:
            url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: testvm1
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - name: disk0
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 1Gi
      volumes:
        - dataVolume:
            name: awesome-dv
          name: disk0
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:12341234
                expire: false
              hostname: vm
              ssh_pwauth: yes
              disable_root: false
          name: cloudinitdisk
